-- This file intentionally remains a stub so SQL Server-oriented analyzers
-- stop flagging errors. The actual Postgres-compatible view definition lives
-- in `supabase/hierarchy_summary.psql`, which is what the Supabase CLI and
-- migrations should execute. Keeping this short note prevents accidental edits
-- in the wrong place while keeping the Problems panel clean.
