const REPO_BASE = "https://github.com/kwo744-075/pocket-manager-app/blob/main";

export type FeatureMeta = {
  slug: string;
  title: string;
  summary: string;
  platformRoute: string;
  docPath?: string;
  forms?: string[];
  keyHooks?: string[];
  tags: string[];
  status: "live" | "beta" | "planned";
};

export const FEATURE_REGISTRY = [
  {
    slug: "daily-log",
    title: "Daily Log",
    summary: "Cash, labor, and inventory closeout workspace that mirrors the Daily Logbook views in the native app.",
    platformRoute: "/(tabs)/(home)/daily-log",
    docPath: "docs/DAILY_LOG_SYSTEM.md",
    forms: ["Daily Summary Report", "Daily Logbook Entries"],
    keyHooks: ["loadProfile", "generateDailySummary", "useTheme"],
    tags: ["operations", "reports"],
    status: "live",
  },
  {
    slug: "turned-log",
    title: "Turned Log",
    summary: "Tracks turned cars, approvals, and photo receipts to align with the Turned Logbook tooling.",
    platformRoute: "/(tabs)/(home)/turned-log",
    docPath: "docs/TURNED_LOG_QUICK_REFERENCE.md",
    forms: ["Turned Vehicle Log"],
    keyHooks: ["loadProfile", "supabase.from('turned_logs')"],
    tags: ["operations", "quality"],
    status: "live",
  },
  {
    slug: "ops",
    title: "OPS Hub",
    summary: "Operations landing pad that links into cadence, labor, inventory, and workbook utilities.",
    platformRoute: "/(tabs)/(home)/ops",
    forms: ["OPS Brief", "Scorecard Export"],
    keyHooks: ["useKpiBoard"],
    tags: ["operations", "navigation"],
    status: "live",
  },
  {
    slug: "mini-pos",
    title: "Mini POS",
    summary: "Lightweight checkout lane with product tiles, clipboard carts, and quick totals.",
    platformRoute: "/(tabs)/(home)/mini-pos",
    forms: ["Mini POS Cart", "Quick Checkout"],
    keyHooks: ["useCart", "useProductTiles"],
    tags: ["sales", "checkout"],
    status: "beta",
  },
  {
    slug: "chatbot",
    title: "AI Assistant",
    summary: "On-device GPT workflow assistant that answers policy questions and drafts visit recaps.",
    platformRoute: "/(tabs)/(home)/chatbot",
    forms: ["Chat Transcript", "Action List"],
    keyHooks: ["useAIAssistant"],
    tags: ["ai", "productivity"],
    status: "beta",
  },
  {
    slug: "dm-schedule",
    title: "DM Schedule",
    summary: "Planning board for district manager shop visits, powered by cadence templates and visit targets.",
    platformRoute: "/(tabs)/(home)/dm-schedule",
    docPath: "docs/DM_SCHEDULE_QUICK_REFERENCE.md",
    forms: ["Visit Plan", "30-60-90"],
    keyHooks: ["useLocalSearchParams", "useVisits"],
    tags: ["visits", "planning"],
    status: "live",
  },
  {
    slug: "dm-logbook",
    title: "DM Logbook",
    summary: "Recent visit entries, scores, and coaching notes shared back with shops.",
    platformRoute: "/(tabs)/(home)/dm-logbook",
    docPath: "docs/DM_SCHEDULE_QA_CHECKLIST.md",
    forms: ["DM Visit Log", "Action Plan"],
    keyHooks: ["supabase.from('dm_visit_logs')"],
    tags: ["visits", "coaching"],
    status: "live",
  },
  {
    slug: "employee-management",
    title: "Employee Management",
    summary: "People directory with tenure math, pipeline tracking, and phone sheet exports.",
    platformRoute: "/(tabs)/(home)/employee-management",
    docPath: "docs/EMPLOYEE_SCHEDULING_FIXES.md",
    forms: ["Employee Profile", "Phone Sheet"],
    keyHooks: ["EmployeePhoneSheet", "formatTenure"],
    tags: ["people", "staffing"],
    status: "live",
  },
  {
    slug: "employee-scheduling",
    title: "Employee Scheduling",
    summary: "Week grid with projections, coverage alerts, and copy/paste tooling shared with the Expo app.",
    platformRoute: "/(tabs)/(home)/employee-scheduling",
    docPath: "docs/EMPLOYEE_SCHEDULING_FIXES.md",
    forms: ["Schedule Template", "Labor Plan"],
    keyHooks: ["supabase.from('employee_shifts')", "supabase.from('weekly_projections')"],
    tags: ["people", "scheduling"],
    status: "live",
  },
  {
    slug: "labor-tracker",
    title: "Labor Tracker",
    summary: "Allowed vs used hours, staff to par %, and weekly variance alerts.",
    platformRoute: "/(tabs)/(home)/labor-tracker",
    forms: ["Labor Plan", "Variance Note"],
    keyHooks: ["supabase.from('labor_tracking')"],
    tags: ["labor", "staffing"],
    status: "live",
  },
  {
    slug: "training-tracker",
    title: "Training Tracker",
    summary: "CTT completions, in-progress counts, and DM cadence status checks.",
    platformRoute: "/(tabs)/(home)/training-tracker",
    docPath: "BATCH_1_TRAINING_IMPLEMENTATION_SUMMARY.md",
    forms: ["Training Checklist", "Coaching Log"],
    keyHooks: ["supabase.from('employee_training')"],
    tags: ["training", "cadence"],
    status: "live",
  },
  {
    slug: "games",
    title: "Games",
    summary: "Interactive training games and challenges with scoring and leaderboards.",
    platformRoute: "/(tabs)/enhanced-games",
    docPath: "docs/GAMES_SYSTEM_IMPLEMENTATION.md",
    forms: ["Game Results", "Leaderboard"],
    keyHooks: ["supabase.from('employee_training_games')", "supabase.from('employee_shop_tycoon')"],
    tags: ["training", "gamification", "engagement"],
    status: "beta",
  },
  {
    slug: "cadence",
    title: "Cadence",
    summary: "Daily + weekly task templates with auto-tracking for DM compliance.",
    platformRoute: "/(tabs)/cadence",
    docPath: "docs/CADENCE_IMPLEMENTATION.md",
    forms: ["Cadence Template", "Completion Log"],
    keyHooks: ["useLocalSearchParams", "useCadenceBoard"],
    tags: ["cadence", "tasks"],
    status: "live",
  },
  {
    slug: "challenges",
    title: "Challenges",
    summary: "Shop and team challenges with completion scoring and prize tracking.",
    platformRoute: "/(tabs)/(home)/challenges",
    forms: ["Challenge Entry", "Progress Photo"],
    keyHooks: ["supabase.from('challenges_log')"],
    tags: ["engagement", "gamification"],
    status: "beta",
  },
  {
    slug: "inventory",
    title: "Inventory",
    summary: "Live counts, oil vs storage breakdowns, and catalog import/export flows.",
    platformRoute: "/(tabs)/(home)/inventory",
    docPath: "docs/INVENTORY_SYSTEM_REBUILD.md",
    forms: ["Inventory Count", "Catalog Upload"],
    keyHooks: ["supabase.from('inventory_counts_v2')"],
    tags: ["inventory", "operations"],
    status: "live",
  },
  {
    slug: "workbook",
    title: "Shop Workbook",
    summary: "Budget vs actual tracker for vendor spend and purchases.",
    platformRoute: "/(tabs)/(home)/shop-workbook",
    forms: ["Vendor Entry", "Budget Adjustment"],
    keyHooks: ["supabase.from('shop_workbook')"],
    tags: ["finance", "planning"],
    status: "live",
  },
  {
    slug: "checkbook",
    title: "Shop Checkbook",
    summary: "Weekly expense ledger with approvals and export support.",
    platformRoute: "/(tabs)/(home)/shop-checkbook",
    forms: ["Expense Entry", "Approval Route"],
    keyHooks: ["supabase.from('shop_checkbook')"],
    tags: ["finance", "compliance"],
    status: "live",
  },
  {
    slug: "supply",
    title: "Supply Ordering",
    summary: "PAR-based supply orders with catalog shortcuts and lead-time notes.",
    platformRoute: "/(tabs)/supplies",
    forms: ["Supply Order", "PO Upload"],
    keyHooks: ["supabase.from('supply_orders')"],
    tags: ["inventory", "procurement"],
    status: "beta",
  },
  {
    slug: "solinks",
    title: "SoLinks",
    summary: "Audit workflows for security camera reviews and footage pulls.",
    platformRoute: "/(tabs)/(home)/solinks",
    forms: ["SoLink Audit", "Follow-up Log"],
    keyHooks: ["supabase.from('solink_audits')"],
    tags: ["safety", "compliance"],
    status: "live",
  },
  {
    slug: "repairs",
    title: "Repairs & Maintenance",
    summary: "Equipment repair intake with vendor routing and lead tracking.",
    platformRoute: "/(tabs)/(home)/repairs-maintenance",
    forms: ["Repair Ticket", "Vendor Follow-up"],
    keyHooks: ["supabase.from('repairs_requests')"],
    tags: ["facilities", "safety"],
    status: "live",
  },
  {
    slug: "claims",
    title: "Claims",
    summary: "Customer, employee, and theft claim packages with media uploads.",
    platformRoute: "/(tabs)/claims",
    forms: ["Customer Claim", "Employee Claim", "Theft Claim"],
    keyHooks: ["supabase.from('claims')"],
    tags: ["compliance", "safety"],
    status: "live",
  },
  {
    slug: "crash-kit",
    title: "Crash Kit",
    summary: "Invoice & work-order management for Crash Champions partnership.",
    platformRoute: "/(tabs)/(home)/crash-kit-home",
    docPath: "docs/CRASH_KIT_SERVICE_CATALOG_INTEGRATION.md",
    forms: ["Crash Intake", "Repair Invoice"],
    keyHooks: ["supabase.from('crash_jobs')"],
    tags: ["facilities", "partners"],
    status: "beta",
  },
  {
    slug: "admin-safety",
    title: "Admin & Safety",
    summary: "Unified dashboard for claims, Solinks, alerts, and compliance trackers.",
    platformRoute: "/(tabs)/(home)/admin-safety",
    forms: ["Incident Report", "Safety Drill Log"],
    keyHooks: ["supabase.from('claims')", "supabase.from('solink_audits')"],
    tags: ["compliance", "safety"],
    status: "live",
  },
  {
    slug: "alerts",
    title: "Shop Alerts",
    summary: "Live broadcast of policy shifts, required follow-ups, and risk notifications.",
    platformRoute: "/(tabs)/(home)/alerts",
    forms: ["Alert Broadcast", "Acknowledge Receipt"],
    keyHooks: ["supabase.from('alerts')"],
    tags: ["communication", "safety"],
    status: "live",
  },
] satisfies FeatureMeta[];

export type FeatureSlug = (typeof FEATURE_REGISTRY)[number]["slug"];

export const FEATURE_LOOKUP: Record<FeatureSlug, FeatureMeta> = FEATURE_REGISTRY.reduce((acc, feature) => {
  acc[feature.slug] = feature;
  return acc;
}, {} as Record<FeatureSlug, FeatureMeta>);

export const getDocUrl = (feature: FeatureMeta) =>
  feature.docPath ? `${REPO_BASE}/${feature.docPath}` : undefined;
